### ISSUE TITLE
回复前缀 prefix占位符 能否在回复中去除

### ISSUE THREAD

**Issue by stars-spark** [StarWishsama/Nameless-Bot#400]
![IMG_20220622_115715.jpg](https://user-images.githubusercontent.com/53867496/174940373-d35d61cf-f135-4209-934f-8c573fbe1104.jpg)

**Comment by Colerar** [comment]
@StarWishsama 考虑默认设为 `null` 或 `Comet`，而不是 `prefix - 占位符`

**Comment by StarWishsama** [comment]
> @StarWishsama 考虑默认设为 `null` 或 `Comet`，而不是 `prefix - 占位符`

这是 i18n 的问题, 在重构时会妥善解决

**Comment by StarWishsama** [comment]
欲暂时解决此问题，请在机器人 jar 文件的目录下创建 /res/i18n/zh_cn.yml。

并填入以下内容：
```
prefix: 'Comet >'
message:
  no-permission: '你没有权限!'
  bind-success: '绑定账号成功!'
  checkin-first-time: '你还没有签到过, 先用 /qd 签到一次吧~'
  no-enough-point: '积分不足 (%point%), 本次使用需要 %cost% 点积分, 可以通过签到 (/qd) 获取积分哦'
  network-error: '获取失败, 请歇一会儿再试吧~'
```

其中内容可自由修改 (除占位符)，重启机器人生效
